import 'server-only';
import {books as fallbackBooks, posts as fallbackPosts, type Book} from '@/lib/data';
import {getLocalBookCover} from '@/lib/book-images';

const API='https://api.notion.com/v1';
type Rich={plain_text:string}; type FileValue={type:'external'|'file';external?:{url:string};file?:{url:string}};
type Property={title?:Rich[];rich_text?:Rich[];select?:{name:string}|null;multi_select?:{name:string}[];checkbox?:boolean;date?:{start:string}|null;files?:FileValue[];url?:string|null;number?:number|null};
type Page={properties:Record<string,Property>};
async function query(id:string|undefined,filter?:Record<string,unknown>){if(!process.env.NOTION_API_KEY||!id)return [] as Page[];try{const r=await fetch(`${API}/databases/${id}/query`,{method:'POST',headers:{Authorization:`Bearer ${process.env.NOTION_API_KEY}`,'Content-Type':'application/json','Notion-Version':'2022-06-28'},body:JSON.stringify(filter?{filter}:{}),next:{revalidate:300}});if(!r.ok){console.error('Notion query failed',r.status,await r.text());return [];}return ((await r.json()) as {results:Page[]}).results;}catch(e){console.error('Notion unavailable',e);return [];}}
const p=(x:Page,n:string)=>x.properties[n]; const text=(x:Page,n:string)=>[...(p(x,n)?.title||[]),...(p(x,n)?.rich_text||[])].map(v=>v.plain_text).join('').trim();
const select=(x:Page,n:string)=>p(x,n)?.select?.name||''; const multi=(x:Page,n:string)=>p(x,n)?.multi_select?.map(v=>v.name)||[]; const checked=(x:Page,n:string)=>Boolean(p(x,n)?.checkbox);
const file=(x:Page,n:string)=>{const f=p(x,n)?.files?.[0];return f?.type==='external'?f.external?.url||'':f?.file?.url||'';};

export type WebsitePhoto={name:string;src:string;alt:string;caption:string;uses:string[];featured:boolean};
export type StudioListing={name:string;ages:string;schedule:string;fee:number|null;format:string;blurb:string;registration:string;poster:string};
export async function getBooks():Promise<Book[]>{const pages=await query(process.env.NOTION_BOOK_LIBRARY_DATABASE_ID,{property:'Website',checkbox:{equals:true}});if(!pages.length)return fallbackBooks;return pages.map((x,i)=>{const title=text(x,'Book');return{title,author:text(x,'Author')||undefined,category:multi(x,'Category')[0]||'Books',age:multi(x,'Age').join(', ')||'All ages',language:multi(x,'Language').join(', ')||undefined,color:['bg-sky','bg-sun','bg-rose','bg-moss','bg-clay'][i%5],image:file(x,'Cover')||getLocalBookCover(title),summary:text(x,'Parent Note')||text(x,'Notes')||'A book selected for curious children and their grown-ups.',learn:text(x,'Try This')||text(x,'Themes'),why:text(x,'Why I Recommend It')||'An Architectmata bookshelf recommendation.'};});}
export async function getPosts(){const pages=await query(process.env.NOTION_CONTENT_BANK_DATABASE_ID,{property:'Website',checkbox:{equals:true}});if(!pages.length)return fallbackPosts;return pages.map(x=>({title:text(x,'Title'),category:select(x,'Category')||select(x,'Pillar')||'Notebook',date:p(x,'Date')?.date?.start||'',excerpt:text(x,'Hook')||text(x,'Notes')||'A note from the Architectmata field notebook.'}));}
export async function getWebsitePhotos(use?:string):Promise<WebsitePhoto[]>{const pages=await query(process.env.NOTION_MEDIA_LIBRARY_DATABASE_ID,{and:[{property:'Website',checkbox:{equals:true}},{property:'Status',select:{equals:'Use'}}]});return pages.map(x=>({name:text(x,'Photo / Asset'),src:file(x,'Photo'),alt:text(x,'Alt text')||text(x,'Photo / Asset'),caption:text(x,'Caption'),uses:multi(x,'Use'),featured:checked(x,'Featured')})).filter(x=>x.src&&(!use||x.uses.includes(use)));}
export async function getStudioListings():Promise<StudioListing[]>{const pages=await query(process.env.NOTION_CLASSES_DATABASE_ID,{property:'Website',checkbox:{equals:true}});return pages.map(x=>({name:text(x,'Class / Workshop'),ages:text(x,'Ages'),schedule:text(x,'Schedule'),fee:p(x,'Fee')?.number??null,format:select(x,'Format'),blurb:text(x,'Website blurb')||text(x,'Notes'),registration:p(x,'Registration link')?.url||'',poster:file(x,'Poster')}));}
