'use client';
import {useMemo,useState} from 'react';
import Image from 'next/image';
import {MagnifyingGlass} from '@/components/icons';
import type {Book} from '@/lib/data';
export default function BookLibrary({books}:{books:Book[]}){
 const [query,setQuery]=useState('');const [cat,setCat]=useState('All');
 const cats=['All',...new Set(books.map(b=>b.category))];
 const shown=useMemo(()=>books.filter(b=>(cat==='All'||b.category===cat)&&`${b.title} ${b.summary} ${b.category}`.toLowerCase().includes(query.toLowerCase())),[query,cat]);
 return <><div className="mb-10 rounded-4xl bg-white/60 p-4 dark:bg-white/5 md:flex md:items-center md:justify-between"><label className="flex items-center gap-3 rounded-full border border-ink/15 px-5 dark:border-paper/15"><MagnifyingGlass/><span className="sr-only">Search book reviews</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search the bookshelf…" className="w-full bg-transparent py-3 outline-none md:w-72"/></label><div className="mt-4 flex gap-2 overflow-x-auto pb-1 md:mt-0">{cats.map(c=><button key={c} onClick={()=>setCat(c)} className={`whitespace-nowrap rounded-full px-4 py-2 text-sm ${cat===c?'bg-ink text-paper dark:bg-paper dark:text-ink':'bg-ink/5 dark:bg-paper/10'}`}>{c}</button>)}</div></div><p className="mb-5 text-sm opacity-60" aria-live="polite">Showing {shown.length} book{shown.length!==1?'s':''}</p><div className="grid gap-8 md:grid-cols-2 lg:grid-cols-3">{shown.map(b=><article key={b.title} className="overflow-hidden rounded-4xl border border-ink/10 bg-white/50 dark:bg-white/5"><div className={`${b.color} relative aspect-[4/3] overflow-hidden text-ink`}>{b.image?<Image src={b.image} alt={`${b.title} photographed with collected rocks`} fill sizes="(min-width:1024px) 33vw, (min-width:768px) 50vw, 100vw" className="object-cover"/>:<div className="m-7 flex h-[calc(100%-3.5rem)] flex-col items-center justify-center rounded-[50%_50%_8px_8px] border border-ink/25 px-5 text-center"><span className="text-xs uppercase tracking-widest">{b.category}</span><h2 className="mt-4 font-serif text-3xl">{b.title}</h2></div>}</div><div className="p-6"><span className="rounded-full bg-sun/30 px-3 py-1 text-xs">Ages {b.age}</span><p className="mt-5 leading-relaxed">{b.summary}</p><dl className="mt-5 space-y-3 border-t border-ink/10 pt-5 text-sm"><div><dt className="font-bold text-clay">What children learn</dt><dd className="mt-1 opacity-70">{b.learn}</dd></div><div><dt className="font-bold text-clay">Why I recommend it</dt><dd className="mt-1 opacity-70">{b.why}</dd></div></dl></div></article>)}</div></>
}
