'use client';
import {useMemo,useState} from 'react';
import {MagnifyingGlass} from '@/components/icons';
import type {Book} from '@/lib/data';
export default function BookLibrary({books}:{books:Book[]}){
 const [query,setQuery]=useState('');
 const shown=useMemo(()=>books.filter(b=>`${b.title} ${b.author??''} ${b.summary} ${b.category} ${b.age} ${b.language??''} ${b.learn} ${b.why}`.toLowerCase().includes(query.toLowerCase())),[books,query]);
 return <><div className="mb-10 border-y border-pencil py-4"><label className="flex max-w-xl items-center gap-3 rounded-full border border-ink/15 px-5 dark:border-paper/15"><MagnifyingGlass/><span className="sr-only">Search book reviews</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search the bookshelf…" className="w-full bg-transparent py-3 outline-none"/></label></div><p className="mb-5 text-sm opacity-60" aria-live="polite">Showing {shown.length} book{shown.length!==1?'s':''}</p><div className="divide-y divide-ink/15 border-y border-ink/15 dark:divide-paper/15 dark:border-paper/15">{shown.map(b=><article key={b.title} className="grid gap-4 py-6 sm:grid-cols-[minmax(0,.75fr)_minmax(0,1.25fr)] sm:gap-8 md:py-8"><div><p className="text-xs uppercase tracking-widest text-clay">{[b.category,b.age&&`Ages ${b.age}`,b.language].filter(Boolean).join(' · ')}</p><h2 className="mt-2 font-serif text-2xl leading-tight md:text-3xl">{b.title}</h2>{b.author&&<p className="mt-2 text-sm opacity-60">by {b.author}</p>}</div><div><p className="leading-relaxed opacity-75">{b.summary}</p>{b.learn&&<p className="mt-3 text-sm"><strong className="text-clay">What children learn:</strong> <span className="opacity-70">{b.learn}</span></p>}{b.why&&<p className="mt-3 text-sm"><strong className="text-clay">Why I recommend it:</strong> <span className="opacity-70">{b.why}</span></p>}</div></article>)}</div>{!shown.length&&<p className="py-16 text-center opacity-60">No books match that search yet.</p>}</>
}
