'use client';
import Link from 'next/link';
import {ArrowUpRight} from '@/components/icons';
import Reveal from '@/components/reveal';
export function Eyebrow({children}:{children:React.ReactNode}){return <p className="mb-4 text-[11px] font-bold uppercase tracking-[.22em] text-clay">{children}</p>}
export function PageHero({eyebrow,title,intro,accent='bg-sky'}:{eyebrow:string,title:string,intro:string,accent?:string}){return <section className="blueprint-paper relative overflow-hidden border-b border-pencil px-5 pb-20 pt-32 md:px-10 md:pb-28 md:pt-44"><div className={`absolute -right-20 top-28 h-64 w-80 rotate-6 border border-ink/15 ${accent} opacity-35 shadow-field`}/><div className="absolute right-12 top-32 h-44 w-44 rounded-full border border-dashed border-ink/20"/><Reveal className="relative mx-auto max-w-7xl"><div className="mb-5 flex items-center gap-3"><span className="h-px w-10 bg-clay"/><Eyebrow>{eyebrow}</Eyebrow></div><h1 className="max-w-5xl font-serif text-5xl leading-[.98] md:text-8xl">{title}</h1><p className="mt-8 max-w-2xl border-l border-pencil pl-5 text-lg leading-relaxed text-ink/70 dark:text-paper/70 md:text-xl">{intro}</p><span className="mt-7 block font-note text-xs opacity-40">ARCHITECTMATA / FIELD NOTE</span></Reveal></section>}
export function SectionHead({eyebrow,title,link,href}:{eyebrow:string,title:string,link?:string,href?:string}){return <div className="mb-12 flex items-end justify-between gap-5 border-t border-pencil pt-5"><div><Eyebrow>{eyebrow}</Eyebrow><h2 className="font-serif text-4xl leading-tight md:text-6xl">{title}</h2></div>{link&&href&&<Link className="focus-ring hidden items-center gap-2 border-b border-ink/40 pb-1 text-sm md:flex" href={href}>{link}<ArrowUpRight/></Link>}</div>}
export function PlaceholderImage({className='',label='A field note in image form',tone='bg-sky'}:{className?:string,label?:string,tone?:string}){return <div role="img" aria-label={label} className={`group relative overflow-hidden rounded-[2rem] ${tone} ${className}`}><div className="absolute -bottom-12 -left-10 h-4/5 w-3/5 rotate-12 rounded-[50%] border-2 border-ink/30"/><div className="absolute right-[15%] top-[12%] h-1/2 w-px -rotate-12 bg-ink/30"/><span className="absolute bottom-5 left-6 font-serif text-sm italic text-ink/70">{label}</span></div>}
export function Newsletter(){return <section className="bg-moss px-5 py-20 text-paper md:px-10"><div className="mx-auto grid max-w-7xl gap-8 md:grid-cols-2 md:items-end"><div><Eyebrow>Notes from the field</Eyebrow><h2 className="font-serif text-4xl md:text-6xl">A thoughtful letter,<br/><em>now and then.</em></h2></div><div><p className="mb-5 text-paper/70">Newsletter signup is coming soon. Email Architectmata to stay in touch.</p><a className="focus-ring inline-flex rounded-full bg-sun px-7 py-4 font-bold text-ink transition hover:-translate-y-1" href="mailto:hello.architectmata@gmail.com?subject=Architectmata%20newsletter">Email Architectmata</a></div></div></section>}
export function ResourceCard({title,type,meta}:{title:string,type:string,meta:string}){return <article className="rounded-4xl border border-ink/15 bg-white/40 p-6 dark:border-paper/15 dark:bg-white/5"><div className="mb-16"><span className="rounded-full bg-sun/40 px-3 py-1 text-xs">{type}</span></div><h3 className="font-serif text-2xl">{title}</h3><p className="mt-2 text-sm opacity-60">{meta}</p></article>}
